
server:
  port: 8091
  undertow:
    io-threads: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 64 # 阻塞任务线程池, undertow会从这个线程池中取得线程,它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    buffer-size: 1024 # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)



spring:
  profiles:
    active: @spring.profiles.active@ #获取运行的参数

  # 热部署配置
  devtools:
    restart:
      enabled: true #设置开启热部署
      additional-paths: src/main/java #重启目录

  # redis 配置
  redis:
    # 单机
    host: 192.168.1.99
    port: 6379

#    # 哨兵
#    sentinel:
#      master: mymaster
#      nodes: 192.168.1.99:26379,192.168.1.99:26380,192.168.1.99:26381  # 哨兵的IP:Port列表

    password: 123456
    timeout: 60000 #连接超时时间，单位毫秒，默认为0
    lettuce: # 或 jedis
      shutdown-timeout: 10000
      pool:
        max-active: 15
        max-wait: 4
        max-idle: 8
        min-idle: 5
    database: 0


#加载log4j2 日志文件
logging:
  config: classpath:log4j/log4j2-dev.xml

# mybatis 配置
mybatis:
  type-aliases-package: com.example.demo.po
  mapper-locations: classpath:com/example/demo/dao/*.xml



sys-param:
  path: classpath:config/param-dev.properties



