spring:
  datasource:
    c3p0:
      #jdbc配置
      user: jk_db
      password: oracle
      jdbcUrl: jdbc:oracle:thin:@192.168.1.70:1521:dba
      driverClass: oracle.jdbc.driver.OracleDriver
      #  c3cp0连接池
      type: com.mchange.v2.c3p0.DriverManagerDataSource #指定自定义连接池类型，不指定则默认使用hikari
      dataSourceName: primary #数据源名字，与上面对应上
      initialPoolSize: 10 #连接池初始化连接数
      idleConnectionTestPeriod: 60 #每 60 秒检查所有连接池中的空闲连接
      numHelperThreads: 3 #开启3个线程
      acquireRetryDelay: 1000  #两次连接中间隔时间，单位毫秒
      checkoutTimeout: 10000  #连接超时时间
      maxIdleTimeExcessConnections: 5
      acquireRetryAttempts: 5 #当连接池中的连接耗尽的时候 c3p0 一次同时获取的连接数
      minPoolSize: 10 #连接池最小连接数
      maxPoolSize: 100 #连接池最大连接数
      maxIdleTime: 60  #最大空闲时间,60 秒内未使用则连接被丢弃。若为 0 则永不丢弃。
      autoCommitOnClose: false  #关闭连接后不自动提交
      preferred-test-query: select 1 from dual



mybatis:
  #  sql语句打印，生产删除
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
